name: Build and Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.12'

      - name: Install dependencies
        run: pip install --no-cache-dir -r requirements.txt

      - name: Build Docker Image
        run: docker build -t wine-quality-predictor:$GITHUB_SHA .

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push Docker Image to Docker Hub
        run: |
          docker tag wine-quality-predictor:$GITHUB_SHA ${{ secrets.DOCKER_HUB_USERNAME }}/wine-quality-predictor:$GITHUB_SHA
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/wine-quality-predictor:$GITHUB_SHA

      - name: Log in to Heroku Container Registry
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          heroku_app_name: "wine-quality-predictor"
          usedocker: true

      - name: Deploy to Heroku
        run: heroku container:release web --app wine-quality-predictor
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
  
      - name: Print URL of deployed app
        run: echo "App is deployed at https://wine-quality-predictor.herokuapp.com"